---
title: "Bibliometric analysis with R"
author: "UDC Ranking's Group"
date: '`r paste0("scimetr ", packageVersion("scimetr"),": ", Sys.Date())`'
output: 
  rmarkdown::html_vignette:
    toc: yes
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Bibliometric analysis with R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Packages for bibliometric analysis

- [bibliometrix](http://www.bibliometrix.org): An R-Tool for Comprehensive Science Mapping Analysis.

    Aria, M. & Cuccurullo, C. (2017). bibliometrix: An R-tool for comprehensive science mapping analysis,
    Journal of Informetrics, 11(4), pp 959-975, Elsevier, 
    DOI: [10.1016/j.joi.2017.08.007](https://doi.org/10.1016/j.joi.2017.08.007).
    
- [CITAN](https://CRAN.R-project.org/package=CITAN):
  CITation ANalysis Toolpack **[DEPRECATED]**.

    Gagolewski, M. (2011). Bibliometric impact assessment with R and the CITAN package,
    Journal of Informetrics, 5(4), pp. 678-692, 
    DOI: [10.1016/j.joi.2011.06.006](https://doi.org/10.1016/j.joi.2011.06.006),
    [revised version](https://www.gagolewski.com/publications/2011citan.pdf).


- [scimetr](https://rubenfcasal.github.io/scimetr/index.html): 
  Analysis of Scientific Publication Data with R.


## Packages for downloading bibliometric data

- [openalexR](https://docs.ropensci.org/openalexR): Getting Bibliographic Records from 'OpenAlex' Database Using 'DSL' API.

- [rcrossref](https://docs.ropensci.org/rcrossref): R interface to CrossRef APIs.

- [rscopus](https://CRAN.R-project.org/package=rscopus): 
  [Scopus Database API](https://dev.elsevier.com/sc_apis.html) Interface.

- [rwos](https://github.com/juba/rwos): 
  R interface with [Web of Science API Lite](https://developer.clarivate.com/apis/woslite) **[ARCHIVED]**.

- ...

<!-- 
- [wosr](https://vt-arc.github.io/wosr/index.html): Clients to the 'Web of Science' and 'InCites' [APIs](https://developer.clarivate.com/apis). 
-->


## ropensci: Transforming science through open data and software
Selecting the *Literature* filter in [ropensci/packages](https://ropensci.org/packages), a list of packages that may be useful in this field is provided.
Among them (in addition to `openalexR` and `rcrossref`) it is worth highlighting:

- [aRxiv](https://docs.ropensci.org/aRxiv): Interface to the arXiv API.
	
- [jstor](https://ropensci.github.io/jstor): Import and Analyse Data from Scientific Articles.

- [fulltext](https://ropenscilabs.github.io/fulltext-book): 
  Full Text of 'Scholarly' Articles Across Many Data Sources.

- [europepmc](https://ropensci.github.io/europepmc): 
  R Interface to the Europe PubMed Central RESTful Web Service.

- [IEEER](https://github.com/ropensci/IEEER): Interface to the IEEE Xplore Gateway **[ARCHIVED]**.

<!-- 
- [crminer](https://docs.ropensci.org/crminer): Fetch 'Scholary' Full Text from 'Crossref'.

- [rorcid](https://ropensci.github.io/rorcid): Interface to the 'Orcid.org' API.

- [rplos](https://docs.ropensci.org/rplos): R client for the PLoS Journals API. 

## Other packages/tools

- [Diderot](https://cran.r-project.org/web/packages/Diderot/index.html)

- https://github.com/topics/bibliometrics?l=r

- ...

-->


